Dump neighbor's MAC from kernel on neighbor_update_interfaces
yanet-platform/yanet pull request #129
Opened 2024-02-19 17:34 UTC by taitov

2024-02-20 14:15 UTC, GeorgyKirichenko approved these changes

2024-02-20 14:15 UTC, GeorgyKirichenko approved these changes

2024-02-20 15:53 UTC, 3Hren requested changes

2024-02-20 15:53 UTC, 3Hren commented on dataplane/neighbor.cpp
> +		memcpy(value.ether_address.addr_bytes, mac_address.data(), 6);
Magic constant `6`.

2024-02-20 15:53 UTC, 3Hren commented on dataplane/neighbor.cpp
> +	send(nl_socket, &request, sizeof(request), 0);
No error handling. Partial send is also theoretically possible.

2024-02-20 15:53 UTC, 3Hren commented on dataplane/neighbor.cpp
> +	static uint32_t sequence = time(nullptr);
Global variables? Then we have possible race condition while doing RMW operation below.

2024-02-21 18:04 UTC, 3Hren approved these changes

2024-02-21 18:30 UTC, merged