multiple-vrfs-stage-1
yanet-platform/yanet pull request #152
Opened 2024-04-03 11:52 UTC by alxblv

separate lpm for each vrf, which are provided in logicalPort sections of controlplane.conf and in rib_update messages

2024-04-09 11:38 UTC, ol-imorozko requested changes

2024-04-09 11:38 UTC, ol-imorozko commented on controlplane/route.cpp
> +		if (vrf_map.count(vrf) == 0)
if we use C++-20 features, than `contains` is a better option

2024-04-09 11:38 UTC, ol-imorozko commented on controlplane/route.cpp
> +		uint32_t vrf_id;
It's better to avoid uninitialized variables.
smth like `uint32_t vrf_id{};` or `uint32_t vrf_id = 0;`
But feel free to ignore

2024-04-09 11:38 UTC, ol-imorozko commented on controlplane/route.cpp
> +		{
same here

2024-04-09 11:38 UTC, ol-imorozko commented on dataplane/globalbase.cpp
> +	updater.route_lpm4[vrf_id] = std::make_unique<updater_lpm4_24bit_8bit>(name,
Using c-style string in modern C++ code is strange.
I think
```cpp
std::string name = "route.v4.lpm_" + std::to_string(vrf_id);

updater.route_lpm4[vrf_id] = std::make_unique<updater_lpm4_24bit_8bit>(name.c_str(),
```
is better

2024-04-09 11:38 UTC, ol-imorozko commented on dataplane/globalbase.cpp
> +	updater.route_lpm6[vrf_id] = std::make_unique<updater_lpm6_8x16bit>(name,
same here

2024-04-09 11:38 UTC, ol-imorozko commented on dataplane/globalbase.cpp
> +	updater.route_tunnel_lpm4[vrf_id] = std::make_unique<updater_lpm4_24bit_8bit>(name,
same here

2024-04-09 11:38 UTC, ol-imorozko commented on dataplane/globalbase.cpp
> +	updater.route_tunnel_lpm6[vrf_id] = std::make_unique<updater_lpm6_8x16bit>(name,
same here

2024-09-20 13:07 UTC, GeorgyKirichenko commented
Obsoleted

2024-09-20 13:07 UTC, closed without merging