Control plane workers config parsing
yanet-platform/yanet pull request #180
Opened 2024-04-22 18:30 UTC by TheRandomCharacter

Adds parsing of control plane workers configuration from config file.
Expected config file section is:
```json
"controlPlaneWorkers": [
    {
        "core" : 42,
        "interfaces": [ <interface_name_string> ]
    }
]
```
In case section is not present, configuration for single control plane worker, responsible for all dataplane interfaces and residing on `controlPlaneCoreId` is generated. This Is done to ease transition on already deployed appliances.

Section is checked for
- Every configured dataplane interface is assigned to a control plane worker
- Each interface is assigned to single control plane worker
- Interfaces not configured for use by dataplane are treated as errors

2024-04-23 11:38 UTC, ol-imorozko commented
Could you also add the description to the commit message?

2024-04-23 12:28 UTC, ol-imorozko requested changes

2024-04-23 16:28 UTC, TheRandomCharacter commented on dataplane/dataplane.cpp
> +	}
and `cpw` will dangle if `if` block executes

2024-04-23 17:03 UTC, ol-imorozko commented on dataplane/dataplane.cpp
> +	}
Oh, that's right, I forgot that `YADECAP_LOG_WARNING` is not terminating

2024-04-24 13:56 UTC, ol-imorozko approved these changes

2024-04-25 15:13 UTC, TheRandomCharacter commented
Fixed the logic and reworked it to configuration in terms of interface names, not dpdk port ids.

2024-04-25 15:19 UTC, ol-imorozko approved these changes

2024-04-26 12:39 UTC, GeorgyKirichenko commented
Good enough but I would prefer to wait with this until the whole work is done.
Also we have to document the configuration changes

2024-05-02 11:38 UTC, ol-imorozko approved these changes

2024-05-02 11:38 UTC, ol-imorozko commented on dataplane/dataplane.cpp
> +	return res;
I think
```cpp
        std::set<InterfaceName> res;
        for (const auto& [_, ifaces] : config.workers) {
             res.insert(ifaces.begin(), ifaces.end());
        }
        return res;
```
is better

2024-05-03 11:33 UTC, ol-imorozko commented on dataplane/dataplane.cpp
> +	return res;
Yea, `_` is shown as unused which is a gcc bug, unfortunately.

But `insert` is still desirable though

2024-05-04 20:06 UTC, GeorgyKirichenko requested changes
Could you please add corresponding test-case just to be sure the new config is parsed well

2024-09-20 13:09 UTC, GeorgyKirichenko commented
Superseded by another PR

2024-09-20 13:09 UTC, closed without merging