Counters optimization
yanet-platform/yanet pull request #204
Opened 2024-06-03 15:23 UTC by stal76

2024-06-04 12:33 UTC, ol-imorozko requested changes

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +		{
I don't like the idea of using some magic value as an error in this private method. We can use `std::optional`.
`std::optional<uint16_t> Allocate()`

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +			}
```cpp
            if (group_mask.all())
            {
                return std::nullopt;
            }
```

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +			uint16_t index = group * 64 + index_in_group;
```cpp
            auto group = static_cast<uint16_t>(group_mask._Find_first());
            if (group >= masks.size() || masks[group].all())
            {
                return std::nullopt;
            }
            auto index_in_group = static_cast<uint16_t>(masks[group]._Find_first());
            uint16_t index = group * BITS_PER_GROUP + index_in_group;
```

`_Find_first` will use `__builtin_ctzll` so there will be no overhead, if that's a concern

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +				return error_in_block_;
`return std::nullopt;`

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +			}
```cpp
            masks[group].set(index_in_group);
            if (masks[group].all())
            {
                group_mask.set(group);
            }
```

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +		uint16_t Free(uint16_t index)
Same thing with the return value here, but here we can just return `bool`

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +			return 0;
```cpp
            if (index >= total_segments)
            {
                return false;
            }

            uint16_t group = index >> GROUP_SHIFT;
            index &= GROUP_MASK;

            if (!masks[group].test(index))
            {
                return false;
            }

            // set bits usage
            masks[group].reset(index);
            if (masks[group].none())
            {
                group_mask.reset(group);
            }

            // change number of free segments
            free_segments++;
            return true;
```

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +
Don't need this

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +	OneSizeBlockInfo sizes_info_[MaxBufferSize + 1];
```
    std::array<OneBlock, total_blocks_> all_blocks_;
    std::array<OneSizeBlockInfo, MaxBufferSize + 1> sizes_info_;
```

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +		if (index_in_block == error_in_block_)
```cpp
        auto index_in_block = block.Allocate();
        if (!index_in_block.has_value())
```

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +		uint32_t result = size_info.head_block * BlockSize + index_in_block * size + IndexBegin;
`uint32_t result = size_info.head_block * BlockSize + index_in_block.value() * size + IndexBegin;`

2024-06-04 12:33 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +		if (block.Free(index) == error_in_block_)
`if (!block.Free(index))`

2024-06-04 13:12 UTC, TheRandomCharacter commented on controlplane/segment_allocator.h
> +	}
`[[nodiscard]]` is unnecessary here.
This function returns list of stored errors requested by caller, not errors encountered during execution of the function.

2024-06-04 13:20 UTC, TheRandomCharacter commented on controlplane/segment_allocator.h
> +	static_assert((BlockSize <= 64 * 64) && (BlockSize >= 64));
`BITS_PER_GROUP` should be derived from mask size as `std::numeric_limits<decltype(OneBlock{}.group_mask)>::digits`

2024-06-05 10:11 UTC, ol-imorozko requested changes

2024-06-05 10:11 UTC, ol-imorozko commented on controlplane/unittest/segment_allocator.cpp
> +	AllocatorBig* allocator = new (data) AllocatorBig();
I think we need `alignas(AllocatorBig)` here so the memory is properly aligned for the type being constructed.

I mean `alignas(AllocatorBig) uint8_t data[sizeof(AllocatorBig)];`

Also there's no need to cast to `(void*)`, just use `memset(data, -1, sizeof(AllocatorBig));`. 
In fact, `alignas(AllocatorBig) uint8_t data[sizeof(AllocatorBig)]  = {-1};` is enough

2024-06-05 12:20 UTC, ol-imorozko commented on controlplane/segment_allocator.h
> +	static_assert((BlockSize <= 64 * 64) && (BlockSize >= 64));
- `OneBlock::group_mask` instead of `OneBlock{}.group_mask`

2024-06-12 21:51 UTC, GeorgyKirichenko commented on controlplane/segment_allocator.h
> +	static_assert((BlockSize <= 64 * 64) && (BlockSize >= 64));
The magic number are bad so please use `static constexpr` or corresponding defines inside the `config` file.

2024-06-12 21:59 UTC, GeorgyKirichenko commented on controlplane/segment_allocator.h
> +#define DISABLE_BIT(v, b) (v) &= ~(((uint64_t)1) << (b))
Bitsets are great if corresponding bit count does not fit into standard unsigned types but if you will use only one predefined type C-way is acceptable for me.
However, the macroses above are not fully correct -there is no guaranties about `v` data type and b value, at least they should include uint64 in the macros names.
Also strong typed `static inline` functions are acceptable here.

2024-06-12 22:03 UTC, GeorgyKirichenko commented on controlplane/counter.h
> +		auto iter_left = (iter_right == segments_start_.begin() ? segments_start_.end() : std::prev(iter_right)); // если тот что справа самый первый, то левее уже никого
Please use english for comments and place the comment just before the line

2024-06-12 22:07 UTC, GeorgyKirichenko commented
I like the new allocator but please find some notes bellow:
 - I feel you can squash the changes relating the allocator from the secon into the third commit
 - Please annotate classes and methods with comments
 - Small brief about allocator algorithm is required
 - The commit message headings could be more informational

2024-06-13 09:37 UTC, TheRandomCharacter commented on controlplane/segment_allocator.h
> +#define DISABLE_BIT(v, b) (v) &= ~(((uint64_t)1) << (b))
`std::bitset` provides a well tested abstraction for "a set of N bits" with de facto standard interface. Not using it means that one is rolling ones own implementation. Is it tested as thoroughly? Is the interface intuiteve to use? And most importantly, does it provide additional or different functionality? If answer to any of this questions is no, on should prefer `std::bitset`

2024-06-13 09:54 UTC, TheRandomCharacter commented on controlplane/segment_allocator.h
> +	static_assert((BlockSize <= 64 * 64) && (BlockSize >= 64));
Placing this constants in `config` is questionable. This breaks `SegmentAllocatjr`  being independent. If configuring this values outside of `SegmentAllocator` is desirable exposing these variable as template parameters is a good option.

2024-08-25 18:48 UTC, GeorgyKirichenko approved these changes

2024-08-25 18:51 UTC, merged