timelimit for sendPakckets autotest stage. Packet receiving rewritten.
yanet-platform/yanet pull request #208
Opened 2024-06-13 12:18 UTC by TheRandomCharacter

New implementation bases on whole stage time limit (2s default equivalent of sum of waits used before) instead of hardcoded 1s header wait and 1s body wait.

Fixes logic of expecting read call on `SOCK_STREAM` to return whole header in one call and body on another single call.

Adds ability to override default 2s timelimit by adding a key-value pair `timelimit: <unsinged int seconds>` in sendPackets stage YAML.

2024-06-13 12:40 UTC, ol-imorozko requested changes

2024-06-13 12:40 UTC, ol-imorozko commented on autotest/autotest.cpp
> +	char* buf = reinterpret_cast<char*>(data);
I don't like `void*`..
IMO it's better to ensure type safety with templated function and overloading:
```cpp
bool readTimeLimited(int fd, char* data, ssize_t len, std::chrono::system_clock::time_point time_to_give_up)
{
    ssize_t ret = 0;
    while (len > 0 && std::chrono::system_clock::now() < time_to_give_up)
    {
        ret = read(fd, data, len);
        switch (ret)
        {
            case 0:
                return false;
            case -1:
                if (errno == EAGAIN || errno == EWOULDBLOCK)
                {
                    std::this_thread::sleep_for(READ_WAIT_UNTIL_RETRY);
                }
                else
                {
                    return false;
                }
                break;
            default:
                len -= ret;
                data += ret;
                break;
        }
    }
    return len == 0;
}

template <typename T>
bool readTimeLimited(int fd, T& data, std::chrono::system_clock::time_point time_to_give_up)
{
    return readTimeLimited(fd, reinterpret_cast<char*>(&data), sizeof(T), time_to_give_up);
}
```

2024-06-13 12:40 UTC, ol-imorozko commented on autotest/autotest.cpp
> +	if (!readTimeLimited(fd, &hdr, sizeof(hdr), time_to_give_up))
`if (!readTimeLimited(fd, hdr, time_to_give_up))`

2024-06-13 14:25 UTC, ol-imorozko requested changes

2024-06-13 14:25 UTC, ol-imorozko commented on autotest/autotest.h
> +
`char*` instead of `void*`

2024-06-13 14:25 UTC, ol-imorozko commented on autotest/autotest.h
> +	return readTimeLimited(fd, reinterpret_cast<void*>(&data), sizeof(data), time_to_give_up);
`char*` instead of `void*`

2024-07-04 09:48 UTC, GeorgyKirichenko approved these changes

2024-07-04 09:48 UTC, merged