wlc mowed to from dataplane to controlplane
yanet-platform/yanet pull request #211
Opened 2024-06-26 11:50 UTC by levon-a-akopian

2024-06-26 11:59 UTC, ol-imorozko commented
Could you please improve the commit message?

Change `wlc moved to from dataplane to controlplane` to `Move wlc from dataplane to controlplane`

Also, add a short description explaining why this change is needed, please

2024-06-26 12:26 UTC, ol-imorozko requested changes

2024-06-26 12:26 UTC, ol-imorozko commented on controlplane/balancer.cpp
> +				}
We will have code duplication here with the following lines:
```cpp
auto it = reals_enabled.find(key);
if (it != reals_enabled.end())
{
	if (it->second.has_value())
	{
		effective_weight = it->second.value();
	}
}
```

I think we can add a private method in `balancer_t` like
```cpp
 template <typename Map>
    std::optional<typename Map::mapped_type::value_type> get_effective_weight(const Map& map, const balancer::real_key_global_t& key) const {
        auto it = map.find(key);
        if (it != map.end() && it->second.has_value()) {
            return it->second.value();
        }
        return std::nullopt;
    }
```

And then use it, for example, with compound initialization:
```cpp
if (auto found_weight = get_effective_weight(reals_wlc_weight, key); found_weight) {
    effective_weight = *found_weight;
}
```

2024-06-26 12:26 UTC, ol-imorozko commented on controlplane/balancer.cpp
> +				}
```cpp
auto found_weight = get_effective_weight(reals_enabled, key);
uint32_t effective_weight = found_weight ? *found_weight : weight;
```

2024-06-26 12:26 UTC, ol-imorozko commented on controlplane/balancer.cpp
> +					connections += it->second;
IMHO
```cpp
if (it != real_connections.end())
{
    connections += it->second;
}
```
is cleaner, but feel free no ignore

2025-02-03 14:18 UTC, ol-imorozko submitted a review, later dismissed

2025-02-03 14:18 UTC, ol-imorozko commented on controlplane/balancer.cpp
> +			(void)ipv6_outer_source_network;
use `YANET_GCC_BUG_UNUSED`

2025-02-03 14:18 UTC, ol-imorozko commented on controlplane/balancer.cpp
> +					(void)socket_id;
and here

2025-02-03 14:27 UTC, ol-imorozko commented on controlplane/balancer.h
> +		}
isn't that equivalent to just 
```suggestion
		if (it != map.end())
		{
			return it->second;
		}
```

2025-02-04 10:05 UTC, ol-imorozko approved these changes

2025-02-04 15:40 UTC, GeorgyKirichenko approved these changes
Please do not make  refactorings like `YANET_GCC_BUG_UNUSED` renaming in the same PR where functional changes are done as this complicates the review process.

Or if you feel such refactoring essential then each commit should be atomic and enabled to review separately , without any further `according to review` references in the following commits.

2025-02-04 15:48 UTC, merged