Ipv4 connectivity
yanet-platform/yanet pull request #262
Opened 2024-12-15 15:16 UTC by stal76

The following functionality has been added to this PR:
- a new tunnel type - IpIp;
- the ability to communicate between local subnets with route tunnel;
- the ability to set route tunnel routes in controlplane.conf;
- the ability to use random source address in route tunnel.

2024-12-16 13:11 UTC, ol-imorozko requested changes

2024-12-16 13:11 UTC, ol-imorozko commented on controlplane/configparser.cpp
> +	}
```suggestion
        route.random_source = moduleJson.value("random_source", false);
```

2024-12-16 13:12 UTC, ol-imorozko commented
overall LGTM

2025-01-29 11:40 UTC, ol-imorozko commented on dataplane/worker.cpp
>  	}
feel free to ignore this in though, it's just a suggestion for later

2025-01-31 15:16 UTC, GeorgyKirichenko approved these changes
LGTM

2025-01-31 15:21 UTC, ol-imorozko approved these changes

2025-01-31 15:21 UTC, merged