[WIP] Add timeouts for tcp syn and tcp ack
yanet-platform/yanet pull request #99
Opened 2024-01-25 10:10 UTC by Gmacem

2024-01-25 10:24 UTC, taitov commented
Hello! Resolve conflicts and use clang-format, please.

2024-01-25 10:35 UTC, 3Hren requested changes

2024-01-25 10:35 UTC, 3Hren commented on dataplane/worker_gc.cpp
> +	return fin_timeout;
Seems strange to see FIN timeout as a "default" value. Maybe it's reasonable to create а real default timeout, while processing FIN timeout explicitly using mask?

2024-01-26 18:27 UTC, 3Hren requested changes

2024-01-26 18:27 UTC, 3Hren commented on dataplane/worker_gc.cpp
> +	if (flags & (RTE_TCP_ACK_FLAG | RTE_TCP_SYN_FLAG))
This condition will be `true` if any of SYN|ACK flags are set ...

2024-01-26 18:27 UTC, 3Hren commented on dataplane/worker_gc.cpp
> +	if (flags & RTE_TCP_SYN_FLAG)
... that means that this condition is unreachable.

2024-01-26 18:48 UTC, 3Hren requested changes

2024-01-26 18:48 UTC, 3Hren commented on dataplane/worker_gc.h
> +	uint16_t get_acl_tcp_timeout(const uint8_t flags, const uint32_t ack_timeout, const uint32_t syn_timeout, const uint32_t fin_timeout, const uint32_t default_timeout);
Well, here we have timeouts' arguments type as `u32`, but return `u16` instead.

2024-01-26 18:48 UTC, 3Hren commented on dataplane/worker_gc.h
> +	uint16_t get_acl_tcp_timeout(const uint8_t flags, const uint32_t ack_timeout, const uint32_t syn_timeout, const uint32_t fin_timeout, const uint32_t default_timeout);
Having function with 5 arguments seems alien. I'd rather obtained concrete timeouts inside the function using `globalbase_atomic` directly.

2024-01-30 17:57 UTC, taitov requested changes

2024-01-30 17:57 UTC, taitov commented on dataplane/worker.cpp
> +			value->tcp_flags = tcpHeader->tcp_flags;
`value` maybe `nullptr`

2024-01-31 07:22 UTC, 3Hren requested changes

2024-01-31 07:22 UTC, 3Hren commented on dataplane/worker_gc.cpp
> +	if ((flags & RTE_TCP_ACK_FLAG) && (flags & RTE_TCP_SYN_FLAG))
I'm not sure this compiles the right way without unnecessary branches.
Consider more straightforward:

```c++
if ((flags & (RTE_TCP_SYN_FLAG | RTE_TCP_ACK_FLAG)) == (RTE_TCP_SYN_FLAG | RTE_TCP_ACK_FLAG)) { ...
```

Or, as you check for SYN_FLAG the next branch bellow, you can unite them both:

```c++
if ((flags & RTE_TCP_SYN_FLAG) == RTE_TCP_SYN_FLAG) {
    if ((flags & RTE_TCP_ACK_FLAG) == RTE_TCP_ACK_FLAG) {
        return fw_state_config.tcp_ack_timeout;
    } else {
        return fw_state_config.tcp_syn_timeout;
    }
}
```

2024-01-31 07:22 UTC, 3Hren commented on dataplane/worker_gc.cpp
> +		return fw_state_config.tcp_ack_timeout;
Following the condition above this should be named as `tcp_syn_ack_timeout`, isn't it?

2024-01-31 08:49 UTC, taitov commented on dataplane/type.h
> +};
You can pack struct like this:
```
struct balancer_state_value_t
{
	uint32_t real_unordered_id;
	uint32_t timestamp_create; ///< @todo: 16bit
	uint16_t timestamp_last_packet;
	uint16_t timestamp_gc;
	uint32_t tcp_flags; ///< 8bit actually
};
```
or:
```
struct balancer_state_value_t
{
	uint32_t real_unordered_id;
	uint16_t tcp_flags; ///< 8bit actually
	uint16_t timestamp_create;
	uint16_t timestamp_last_packet;
	uint16_t timestamp_gc;
	uint32_t nap0; ///< @todo: DELETE
};
```

2024-01-31 08:49 UTC, taitov commented on dataplane/worker_gc.cpp
> +			// if ((uint16_t)((uint16_t)globalbase_atomic->currentTime - (uint16_t)iter.value()->timestamp_last_packet) > balancer_state_ttl) {
`currentTime` - is 32bit, `timestamp_last_packet` - 16bit.
The result of subtracting these values will always be greater than 60.

2024-02-01 08:15 UTC, 3Hren approved these changes
LGTM

2024-02-01 08:18 UTC, 3Hren commented
Still, we have u32 -> u16 implicit conversions. Delegate further review to @taitov.

2024-02-02 12:44 UTC, taitov requested changes

2024-02-02 12:44 UTC, taitov commented on dataplane/dataplane.cpp
> +	                {eConfigType::balancer_state_ht_size, YANET_CONFIG_BALANCER_STATE_HT_SIZE},
Duplicate `balancer_state_ttl` and `balancer_state_ht_size`

2024-02-02 12:44 UTC, taitov commented on dataplane/dataplane.cpp
> +		configValues[eConfigType::balancer_tcp_fin_timeout] = json["balancer_tcp_timeout"];
`}` ?

2024-02-02 12:44 UTC, taitov commented on dataplane/worker_gc.cpp
> +			if ((uint16_t)((uint16_t)globalbase_atomic->currentTime - (uint16_t)iter.value()->timestamp_last_packet) > tcp_timeout)
For 16bit timestamps, you can use `is_timeout()`

2024-02-02 12:44 UTC, taitov commented on dataplane/worker_gc.cpp
> +inline uint32_t worker_gc_t::get_balancer_tcp_timeout(const uint8_t flags, const dataplane::globalBase::balancer_state_config_t& balancer_state_config)
... and write one function with `const state_config_t& state_config`

2024-02-02 15:08 UTC, GeorgyKirichenko requested changes

2024-02-06 12:43 UTC, GeorgyKirichenko submitted a review, later dismissed
LGTM

2024-02-06 13:53 UTC, taitov commented on dataplane/type.h
> -	uint32_t nap0; ///< @todo: DELETE
Then just rename `nap0` to `state_timeout`

2024-02-06 13:53 UTC, taitov commented on dataplane/worker_gc.cpp
> +				auto value = *iter.value();
Why you copy `value` in this place? Maybe use pointer `auto* value = iter.value()`?

2024-02-06 14:19 UTC, taitov approved these changes

2024-02-06 14:45 UTC, merged